COMMON: &COMMON
  site: 'http://localhost'
  port: 8888
  path_prefex: 'rest/v1'
  username: 'root'
  password: 'secret'
  
development:
  <<: *COMMON

test:
  <<: *COMMON

production:
  <<: *COMMON
  