COMMON: &COMMON
  host: http://localhost
  port: 8888
  path_prefix: rest/v1
  username: root
  password: secret
  subject_namespace: RailsDB
  
development:
  <<: *COMMON

test:
  <<: *COMMON

production:
  <<: *COMMON
  